/*
 * NovaLab API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using NovaLab.ApiClient.Client;
using NovaLab.ApiClient.Api;

namespace NovaLab.ApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing AccessTokenApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AccessTokenApiTests : IDisposable
    {
        private AccessTokenApi instance;

        public AccessTokenApiTests()
        {
            instance = new AccessTokenApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccessTokenApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AccessTokenApi
            //Assert.IsType<AccessTokenApi>(instance);
        }

        /// <summary>
        /// Test ApiUserIdTwitchTokensRefreshGet
        /// </summary>
        [Fact]
        public void ApiUserIdTwitchTokensRefreshGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userId = null;
            //instance.ApiUserIdTwitchTokensRefreshGet(userId);
        }
    }
}
