/*
 * NovaLab API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using NovaLab.ApiClient.Client;
using NovaLab.ApiClient.Api;

namespace NovaLab.ApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing NovaLabVersion1000CultureneutralPublicKeyTokennullApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class NovaLabVersion1000CultureneutralPublicKeyTokennullApiTests : IDisposable
    {
        private NovaLabVersion1000CultureneutralPublicKeyTokennullApi instance;

        public NovaLabVersion1000CultureneutralPublicKeyTokennullApiTests()
        {
            instance = new NovaLabVersion1000CultureneutralPublicKeyTokennullApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NovaLabVersion1000CultureneutralPublicKeyTokennullApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' NovaLabVersion1000CultureneutralPublicKeyTokennullApi
            //Assert.IsType<NovaLabVersion1000CultureneutralPublicKeyTokennullApi>(instance);
        }

        /// <summary>
        /// Test AccountLogoutPost
        /// </summary>
        [Fact]
        public void AccountLogoutPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string returnUrl = null;
            //instance.AccountLogoutPost(returnUrl);
        }

        /// <summary>
        /// Test AccountManageDownloadPersonalDataPost
        /// </summary>
        [Fact]
        public void AccountManageDownloadPersonalDataPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.AccountManageDownloadPersonalDataPost();
        }

        /// <summary>
        /// Test AccountManageLinkExternalLoginPost
        /// </summary>
        [Fact]
        public void AccountManageLinkExternalLoginPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string provider = null;
            //instance.AccountManageLinkExternalLoginPost(provider);
        }

        /// <summary>
        /// Test AccountPerformExternalLoginPost
        /// </summary>
        [Fact]
        public void AccountPerformExternalLoginPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string provider = null;
            //string returnUrl = null;
            //instance.AccountPerformExternalLoginPost(provider, returnUrl);
        }
    }
}
