/*
 * NovaLab API
 *
 * An ASP.NET Core Web API for managing your streams
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using NovaLab.ApiClient.Client;
using NovaLab.ApiClient.Api;
// uncomment below to import models
//using NovaLab.ApiClient.Model;

namespace NovaLab.ApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing TwitchFollowerGoalApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TwitchFollowerGoalApiTests : IDisposable
    {
        private TwitchFollowerGoalApi instance;

        public TwitchFollowerGoalApiTests()
        {
            instance = new TwitchFollowerGoalApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TwitchFollowerGoalApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' TwitchFollowerGoalApi
            //Assert.IsType<TwitchFollowerGoalApi>(instance);
        }

        /// <summary>
        /// Test GetFollowerGoals
        /// </summary>
        [Fact]
        public void GetFollowerGoalsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? userId = null;
            //List<Guid>? goalIds = null;
            //int? limit = null;
            //var response = instance.GetFollowerGoals(userId, goalIds, limit);
            //Assert.IsType<TwitchFollowerGoalDtoApiResult>(response);
        }

        /// <summary>
        /// Test PostFollowerGoal
        /// </summary>
        [Fact]
        public void PostFollowerGoalTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PostFollowerGoalDto? postFollowerGoalDto = null;
            //var response = instance.PostFollowerGoal(postFollowerGoalDto);
            //Assert.IsType<TwitchFollowerGoalDtoApiResult>(response);
        }
    }
}
