/*
 * NovaLab API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using NovaLab.ApiClient.Client;
using NovaLab.ApiClient.Api;
// uncomment below to import models
//using NovaLab.ApiClient.Model;

namespace NovaLab.ApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing TwitchManagedRewardApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TwitchManagedRewardApiTests : IDisposable
    {
        private TwitchManagedRewardApi instance;

        public TwitchManagedRewardApiTests()
        {
            instance = new TwitchManagedRewardApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TwitchManagedRewardApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' TwitchManagedRewardApi
            //Assert.IsType<TwitchManagedRewardApi>(instance);
        }

        /// <summary>
        /// Test ApiUserIdTwitchManagedRewardsGet
        /// </summary>
        [Fact]
        public void ApiUserIdTwitchManagedRewardsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userId = null;
            //int? limit = null;
            //instance.ApiUserIdTwitchManagedRewardsGet(userId, limit);
        }

        /// <summary>
        /// Test ApiUserIdTwitchManagedRewardsPost
        /// </summary>
        [Fact]
        public void ApiUserIdTwitchManagedRewardsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userId = null;
            //CreateCustomRewardsRequest? createCustomRewardsRequest = null;
            //instance.ApiUserIdTwitchManagedRewardsPost(userId, createCustomRewardsRequest);
        }
    }
}
