/*
 * NovaLab API
 *
 * An ASP.NET Core Web API for managing your streams
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using NovaLab.ApiClient.Client;
using NovaLab.ApiClient.Api;
// uncomment below to import models
//using NovaLab.ApiClient.Model;

namespace NovaLab.ApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing TwitchNewFollowerApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TwitchNewFollowerApiTests : IDisposable
    {
        private TwitchNewFollowerApi instance;

        public TwitchNewFollowerApiTests()
        {
            instance = new TwitchNewFollowerApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TwitchNewFollowerApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' TwitchNewFollowerApi
            //Assert.IsType<TwitchNewFollowerApi>(instance);
        }

        /// <summary>
        /// Test PostNewFollower
        /// </summary>
        [Fact]
        public void PostNewFollowerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PostNewFollowerDto? postNewFollowerDto = null;
            //var response = instance.PostNewFollower(postNewFollowerDto);
            //Assert.IsType<NewFollowerDtoApiResult>(response);
        }
    }
}
