/*
 * NovaLab API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using NovaLab.ApiClient.Client;
using NovaLab.ApiClient.Api;
// uncomment below to import models
//using NovaLab.ApiClient.Model;

namespace NovaLab.ApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing TwitchManagedRewardRedemptionApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TwitchManagedRewardRedemptionApiTests : IDisposable
    {
        private TwitchManagedRewardRedemptionApi instance;

        public TwitchManagedRewardRedemptionApiTests()
        {
            instance = new TwitchManagedRewardRedemptionApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TwitchManagedRewardRedemptionApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' TwitchManagedRewardRedemptionApi
            //Assert.IsType<TwitchManagedRewardRedemptionApi>(instance);
        }

        /// <summary>
        /// Test ApiUserIdTwitchManagedRewardsRedemptionsGet
        /// </summary>
        [Fact]
        public void ApiUserIdTwitchManagedRewardsRedemptionsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userId = null;
            //Guid? rewardId = null;
            //DateTime? after = null;
            //int? limit = null;
            //instance.ApiUserIdTwitchManagedRewardsRedemptionsGet(userId, rewardId, after, limit);
        }

        /// <summary>
        /// Test ApiUserIdTwitchManagedRewardsRedemptionsPost
        /// </summary>
        [Fact]
        public void ApiUserIdTwitchManagedRewardsRedemptionsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userId = null;
            //TwitchManagedRewardRedemptionDto? twitchManagedRewardRedemptionDto = null;
            //instance.ApiUserIdTwitchManagedRewardsRedemptionsPost(userId, twitchManagedRewardRedemptionDto);
        }
    }
}
