/*
 * NovaLab.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace NovaLab.ApiClient.Test.Model;

/// <summary>
///     Class for testing HttpStatusCode
/// </summary>
/// <remarks>
///     This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
///     Please update the test case below to test the model.
/// </remarks>
public class HttpStatusCodeTests : IDisposable {
    // TODO uncomment below to declare an instance variable for HttpStatusCode
    //private HttpStatusCode instance;

    public void Dispose() {
        // Cleanup when everything is done.
    }

    /// <summary>
    ///     Test an instance of HttpStatusCode
    /// </summary>
    [Fact]
    public void HttpStatusCodeInstanceTest() {
        // TODO uncomment below to test "IsType" HttpStatusCode
        //Assert.IsType<HttpStatusCode>(instance);
    }
}
