/*
 * NovaLab API
 *
 * An ASP.NET Core Web API for managing your streams
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using NovaLab.ApiClient.Api;
using NovaLab.ApiClient.Model;
using NovaLab.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace NovaLab.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing NewFollowerDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NewFollowerDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NewFollowerDto
        //private NewFollowerDto instance;

        public NewFollowerDtoTests()
        {
            // TODO uncomment below to create an instance of NewFollowerDto
            //instance = new NewFollowerDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NewFollowerDto
        /// </summary>
        [Fact]
        public void NewFollowerDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" NewFollowerDto
            //Assert.IsType<NewFollowerDto>(instance);
        }


        /// <summary>
        /// Test the property 'NewFollowerId'
        /// </summary>
        [Fact]
        public void NewFollowerIdTest()
        {
            // TODO unit test for the property 'NewFollowerId'
        }
        /// <summary>
        /// Test the property 'FollowerGoalId'
        /// </summary>
        [Fact]
        public void FollowerGoalIdTest()
        {
            // TODO unit test for the property 'FollowerGoalId'
        }
        /// <summary>
        /// Test the property 'TimeStamp'
        /// </summary>
        [Fact]
        public void TimeStampTest()
        {
            // TODO unit test for the property 'TimeStamp'
        }
        /// <summary>
        /// Test the property 'FollowerTwitchUserId'
        /// </summary>
        [Fact]
        public void FollowerTwitchUserIdTest()
        {
            // TODO unit test for the property 'FollowerTwitchUserId'
        }

    }

}
