/*
 * NovaLab API
 *
 * An ASP.NET Core Web API for managing your streams
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using NovaLab.ApiClient.Api;
using NovaLab.ApiClient.Model;
using NovaLab.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace NovaLab.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing PostTwitchManagedRewardRedemptionDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostTwitchManagedRewardRedemptionDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostTwitchManagedRewardRedemptionDto
        //private PostTwitchManagedRewardRedemptionDto instance;

        public PostTwitchManagedRewardRedemptionDtoTests()
        {
            // TODO uncomment below to create an instance of PostTwitchManagedRewardRedemptionDto
            //instance = new PostTwitchManagedRewardRedemptionDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostTwitchManagedRewardRedemptionDto
        /// </summary>
        [Fact]
        public void PostTwitchManagedRewardRedemptionDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" PostTwitchManagedRewardRedemptionDto
            //Assert.IsType<PostTwitchManagedRewardRedemptionDto>(instance);
        }


        /// <summary>
        /// Test the property 'ManagedRewardId'
        /// </summary>
        [Fact]
        public void ManagedRewardIdTest()
        {
            // TODO unit test for the property 'ManagedRewardId'
        }
        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [Fact]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
