/*
 * NovaLab API
 *
 * An ASP.NET Core Web API for managing your streams
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using NovaLab.ApiClient.Api;
using NovaLab.ApiClient.Model;
using NovaLab.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace NovaLab.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing PostManagedRewardDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostManagedRewardDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostManagedRewardDto
        //private PostManagedRewardDto instance;

        public PostManagedRewardDtoTests()
        {
            // TODO uncomment below to create an instance of PostManagedRewardDto
            //instance = new PostManagedRewardDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostManagedRewardDto
        /// </summary>
        [Fact]
        public void PostManagedRewardDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" PostManagedRewardDto
            //Assert.IsType<PostManagedRewardDto>(instance);
        }


        /// <summary>
        /// Test the property 'TwitchApiRequest'
        /// </summary>
        [Fact]
        public void TwitchApiRequestTest()
        {
            // TODO unit test for the property 'TwitchApiRequest'
        }
        /// <summary>
        /// Test the property 'OutputTemplatePerReward'
        /// </summary>
        [Fact]
        public void OutputTemplatePerRewardTest()
        {
            // TODO unit test for the property 'OutputTemplatePerReward'
        }
        /// <summary>
        /// Test the property 'OutputTemplatePerRedemption'
        /// </summary>
        [Fact]
        public void OutputTemplatePerRedemptionTest()
        {
            // TODO unit test for the property 'OutputTemplatePerRedemption'
        }

    }

}
