/*
 * NovaLab.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace NovaLab.ApiClient.Test.Model;

/// <summary>
///     Class for testing TrackedStreamSubjectDtoIApiResult
/// </summary>
/// <remarks>
///     This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
///     Please update the test case below to test the model.
/// </remarks>
public class TrackedStreamSubjectDtoIApiResultTests : IDisposable {
    // TODO uncomment below to declare an instance variable for TrackedStreamSubjectDtoIApiResult
    //private TrackedStreamSubjectDtoIApiResult instance;

    public void Dispose() {
        // Cleanup when everything is done.
    }

    /// <summary>
    ///     Test an instance of TrackedStreamSubjectDtoIApiResult
    /// </summary>
    [Fact]
    public void TrackedStreamSubjectDtoIApiResultInstanceTest() {
        // TODO uncomment below to test "IsType" TrackedStreamSubjectDtoIApiResult
        //Assert.IsType<TrackedStreamSubjectDtoIApiResult>(instance);
    }

    /// <summary>
    ///     Test the property 'Status'
    /// </summary>
    [Fact]
    public void StatusTest() {
        // TODO unit test for the property 'Status'
    }

    /// <summary>
    ///     Test the property 'Message'
    /// </summary>
    [Fact]
    public void MessageTest() {
        // TODO unit test for the property 'Message'
    }

    /// <summary>
    ///     Test the property 'Data'
    /// </summary>
    [Fact]
    public void DataTest() {
        // TODO unit test for the property 'Data'
    }
}
