/*
 * NovaLab.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace NovaLab.ApiClient.Test.Model;

/// <summary>
///     Class for testing TrackedStreamSubjectDto
/// </summary>
/// <remarks>
///     This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
///     Please update the test case below to test the model.
/// </remarks>
public class TrackedStreamSubjectDtoTests : IDisposable {
    // TODO uncomment below to declare an instance variable for TrackedStreamSubjectDto
    //private TrackedStreamSubjectDto instance;

    public void Dispose() {
        // Cleanup when everything is done.
    }

    /// <summary>
    ///     Test an instance of TrackedStreamSubjectDto
    /// </summary>
    [Fact]
    public void TrackedStreamSubjectDtoInstanceTest() {
        // TODO uncomment below to test "IsType" TrackedStreamSubjectDto
        //Assert.IsType<TrackedStreamSubjectDto>(instance);
    }

    /// <summary>
    ///     Test the property 'Id'
    /// </summary>
    [Fact]
    public void IdTest() {
        // TODO unit test for the property 'Id'
    }

    /// <summary>
    ///     Test the property 'NovaLabUserId'
    /// </summary>
    [Fact]
    public void NovaLabUserIdTest() {
        // TODO unit test for the property 'NovaLabUserId'
    }

    /// <summary>
    ///     Test the property 'TwitchGameId'
    /// </summary>
    [Fact]
    public void TwitchGameIdTest() {
        // TODO unit test for the property 'TwitchGameId'
    }

    /// <summary>
    ///     Test the property 'TwitchBroadcastLanguage'
    /// </summary>
    [Fact]
    public void TwitchBroadcastLanguageTest() {
        // TODO unit test for the property 'TwitchBroadcastLanguage'
    }

    /// <summary>
    ///     Test the property 'TwitchTitle'
    /// </summary>
    [Fact]
    public void TwitchTitleTest() {
        // TODO unit test for the property 'TwitchTitle'
    }

    /// <summary>
    ///     Test the property 'TwitchTags'
    /// </summary>
    [Fact]
    public void TwitchTagsTest() {
        // TODO unit test for the property 'TwitchTags'
    }

    /// <summary>
    ///     Test the property 'TrackedStreamSubjectComponentId'
    /// </summary>
    [Fact]
    public void TrackedStreamSubjectComponentIdTest() {
        // TODO unit test for the property 'TrackedStreamSubjectComponentId'
    }
}
