/*
 * NovaLab API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using NovaLab.ApiClient.Api;
using NovaLab.ApiClient.Model;
using NovaLab.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace NovaLab.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TwitchManagedRewardApiResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TwitchManagedRewardApiResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TwitchManagedRewardApiResult
        //private TwitchManagedRewardApiResult instance;

        public TwitchManagedRewardApiResultTests()
        {
            // TODO uncomment below to create an instance of TwitchManagedRewardApiResult
            //instance = new TwitchManagedRewardApiResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TwitchManagedRewardApiResult
        /// </summary>
        [Fact]
        public void TwitchManagedRewardApiResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" TwitchManagedRewardApiResult
            //Assert.IsType<TwitchManagedRewardApiResult>(instance);
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
