/*
 * NovaLab API
 *
 * An ASP.NET Core Web API for managing your streams
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using NovaLab.ApiClient.Api;
using NovaLab.ApiClient.Model;
using NovaLab.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace NovaLab.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TwitchFollowerGoal
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TwitchFollowerGoalTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TwitchFollowerGoal
        //private TwitchFollowerGoal instance;

        public TwitchFollowerGoalTests()
        {
            // TODO uncomment below to create an instance of TwitchFollowerGoal
            //instance = new TwitchFollowerGoal();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TwitchFollowerGoal
        /// </summary>
        [Fact]
        public void TwitchFollowerGoalInstanceTest()
        {
            // TODO uncomment below to test "IsType" TwitchFollowerGoal
            //Assert.IsType<TwitchFollowerGoal>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
        /// <summary>
        /// Test the property 'DailyGoal'
        /// </summary>
        [Fact]
        public void DailyGoalTest()
        {
            // TODO unit test for the property 'DailyGoal'
        }
        /// <summary>
        /// Test the property 'CustomCssStyling'
        /// </summary>
        [Fact]
        public void CustomCssStylingTest()
        {
            // TODO unit test for the property 'CustomCssStyling'
        }

    }

}
