/*
 * NovaLab API
 *
 * An ASP.NET Core Web API for managing your streams
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using NovaLab.ApiClient.Api;
using NovaLab.ApiClient.Model;
using NovaLab.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace NovaLab.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TwitchManagedRewardDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TwitchManagedRewardDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TwitchManagedRewardDto
        //private TwitchManagedRewardDto instance;

        public TwitchManagedRewardDtoTests()
        {
            // TODO uncomment below to create an instance of TwitchManagedRewardDto
            //instance = new TwitchManagedRewardDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TwitchManagedRewardDto
        /// </summary>
        [Fact]
        public void TwitchManagedRewardDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" TwitchManagedRewardDto
            //Assert.IsType<TwitchManagedRewardDto>(instance);
        }


        /// <summary>
        /// Test the property 'ManagedRewardId'
        /// </summary>
        [Fact]
        public void ManagedRewardIdTest()
        {
            // TODO unit test for the property 'ManagedRewardId'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'TwitchBroadcasterId'
        /// </summary>
        [Fact]
        public void TwitchBroadcasterIdTest()
        {
            // TODO unit test for the property 'TwitchBroadcasterId'
        }
        /// <summary>
        /// Test the property 'TwitchRewardId'
        /// </summary>
        [Fact]
        public void TwitchRewardIdTest()
        {
            // TODO unit test for the property 'TwitchRewardId'
        }
        /// <summary>
        /// Test the property 'OutputTemplatePerRedemption'
        /// </summary>
        [Fact]
        public void OutputTemplatePerRedemptionTest()
        {
            // TODO unit test for the property 'OutputTemplatePerRedemption'
        }
        /// <summary>
        /// Test the property 'OutputTemplatePerReward'
        /// </summary>
        [Fact]
        public void OutputTemplatePerRewardTest()
        {
            // TODO unit test for the property 'OutputTemplatePerReward'
        }

    }

}
