/*
 * NovaLab API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using NovaLab.ApiClient.Api;
using NovaLab.ApiClient.Model;
using NovaLab.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace NovaLab.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TwitchManagedReward
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TwitchManagedRewardTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TwitchManagedReward
        //private TwitchManagedReward instance;

        public TwitchManagedRewardTests()
        {
            // TODO uncomment below to create an instance of TwitchManagedReward
            //instance = new TwitchManagedReward();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TwitchManagedReward
        /// </summary>
        [Fact]
        public void TwitchManagedRewardInstanceTest()
        {
            // TODO uncomment below to test "IsType" TwitchManagedReward
            //Assert.IsType<TwitchManagedReward>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
        /// <summary>
        /// Test the property 'RewardId'
        /// </summary>
        [Fact]
        public void RewardIdTest()
        {
            // TODO unit test for the property 'RewardId'
        }
        /// <summary>
        /// Test the property 'OutputTemplatePerReward'
        /// </summary>
        [Fact]
        public void OutputTemplatePerRewardTest()
        {
            // TODO unit test for the property 'OutputTemplatePerReward'
        }
        /// <summary>
        /// Test the property 'OutputTemplate'
        /// </summary>
        [Fact]
        public void OutputTemplateTest()
        {
            // TODO unit test for the property 'OutputTemplate'
        }
        /// <summary>
        /// Test the property 'LastCleared'
        /// </summary>
        [Fact]
        public void LastClearedTest()
        {
            // TODO unit test for the property 'LastCleared'
        }

    }

}
