/*
 * NovaLab API
 *
 * An ASP.NET Core Web API for managing your streams
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using NovaLab.ApiClient.Api;
using NovaLab.ApiClient.Model;
using NovaLab.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace NovaLab.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TwitchFollowerGoalDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TwitchFollowerGoalDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TwitchFollowerGoalDto
        //private TwitchFollowerGoalDto instance;

        public TwitchFollowerGoalDtoTests()
        {
            // TODO uncomment below to create an instance of TwitchFollowerGoalDto
            //instance = new TwitchFollowerGoalDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TwitchFollowerGoalDto
        /// </summary>
        [Fact]
        public void TwitchFollowerGoalDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" TwitchFollowerGoalDto
            //Assert.IsType<TwitchFollowerGoalDto>(instance);
        }


        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'GoalId'
        /// </summary>
        [Fact]
        public void GoalIdTest()
        {
            // TODO unit test for the property 'GoalId'
        }
        /// <summary>
        /// Test the property 'DailyGoalAmount'
        /// </summary>
        [Fact]
        public void DailyGoalAmountTest()
        {
            // TODO unit test for the property 'DailyGoalAmount'
        }
        /// <summary>
        /// Test the property 'Divider'
        /// </summary>
        [Fact]
        public void DividerTest()
        {
            // TODO unit test for the property 'Divider'
        }
        /// <summary>
        /// Test the property 'CustomCssStyling'
        /// </summary>
        [Fact]
        public void CustomCssStylingTest()
        {
            // TODO unit test for the property 'CustomCssStyling'
        }

    }

}
