/*
 * NovaLab API
 *
 * An ASP.NET Core Web API for managing your streams
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using NovaLab.ApiClient.Api;
using NovaLab.ApiClient.Model;
using NovaLab.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace NovaLab.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TwitchManagedStreamSubjectDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TwitchManagedStreamSubjectDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TwitchManagedStreamSubjectDto
        //private TwitchManagedStreamSubjectDto instance;

        public TwitchManagedStreamSubjectDtoTests()
        {
            // TODO uncomment below to create an instance of TwitchManagedStreamSubjectDto
            //instance = new TwitchManagedStreamSubjectDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TwitchManagedStreamSubjectDto
        /// </summary>
        [Fact]
        public void TwitchManagedStreamSubjectDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" TwitchManagedStreamSubjectDto
            //Assert.IsType<TwitchManagedStreamSubjectDto>(instance);
        }


        /// <summary>
        /// Test the property 'SelectionName'
        /// </summary>
        [Fact]
        public void SelectionNameTest()
        {
            // TODO unit test for the property 'SelectionName'
        }
        /// <summary>
        /// Test the property 'ObsSubjectTitle'
        /// </summary>
        [Fact]
        public void ObsSubjectTitleTest()
        {
            // TODO unit test for the property 'ObsSubjectTitle'
        }
        /// <summary>
        /// Test the property 'TwitchSubjectTitle'
        /// </summary>
        [Fact]
        public void TwitchSubjectTitleTest()
        {
            // TODO unit test for the property 'TwitchSubjectTitle'
        }

    }

}
