/*
 * NovaLab API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using NovaLab.ApiClient.Api;
using NovaLab.ApiClient.Model;
using NovaLab.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace NovaLab.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TwitchManagedRewardRedemption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TwitchManagedRewardRedemptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TwitchManagedRewardRedemption
        //private TwitchManagedRewardRedemption instance;

        public TwitchManagedRewardRedemptionTests()
        {
            // TODO uncomment below to create an instance of TwitchManagedRewardRedemption
            //instance = new TwitchManagedRewardRedemption();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TwitchManagedRewardRedemption
        /// </summary>
        [Fact]
        public void TwitchManagedRewardRedemptionInstanceTest()
        {
            // TODO uncomment below to test "IsType" TwitchManagedRewardRedemption
            //Assert.IsType<TwitchManagedRewardRedemption>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'TwitchManagedReward'
        /// </summary>
        [Fact]
        public void TwitchManagedRewardTest()
        {
            // TODO unit test for the property 'TwitchManagedReward'
        }
        /// <summary>
        /// Test the property 'TimeStamp'
        /// </summary>
        [Fact]
        public void TimeStampTest()
        {
            // TODO unit test for the property 'TimeStamp'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
