/*
 * NovaLab API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using NovaLab.ApiClient.Api;
using NovaLab.ApiClient.Model;
using NovaLab.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace NovaLab.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TwitchManagedRewardRedemptionApiResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TwitchManagedRewardRedemptionApiResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TwitchManagedRewardRedemptionApiResult
        //private TwitchManagedRewardRedemptionApiResult instance;

        public TwitchManagedRewardRedemptionApiResultTests()
        {
            // TODO uncomment below to create an instance of TwitchManagedRewardRedemptionApiResult
            //instance = new TwitchManagedRewardRedemptionApiResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TwitchManagedRewardRedemptionApiResult
        /// </summary>
        [Fact]
        public void TwitchManagedRewardRedemptionApiResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" TwitchManagedRewardRedemptionApiResult
            //Assert.IsType<TwitchManagedRewardRedemptionApiResult>(instance);
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
