/*
 * NovaLab API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using NovaLab.ApiClient.Api;
using NovaLab.ApiClient.Model;
using NovaLab.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace NovaLab.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TwitchManagedRewardRedemptionDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TwitchManagedRewardRedemptionDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TwitchManagedRewardRedemptionDto
        //private TwitchManagedRewardRedemptionDto instance;

        public TwitchManagedRewardRedemptionDtoTests()
        {
            // TODO uncomment below to create an instance of TwitchManagedRewardRedemptionDto
            //instance = new TwitchManagedRewardRedemptionDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TwitchManagedRewardRedemptionDto
        /// </summary>
        [Fact]
        public void TwitchManagedRewardRedemptionDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" TwitchManagedRewardRedemptionDto
            //Assert.IsType<TwitchManagedRewardRedemptionDto>(instance);
        }


        /// <summary>
        /// Test the property 'RewardId'
        /// </summary>
        [Fact]
        public void RewardIdTest()
        {
            // TODO unit test for the property 'RewardId'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
