/*
 * NovaLab API
 *
 * An ASP.NET Core Web API for managing your streams
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NovaLab.ApiClient.Client;
using NovaLab.ApiClient.Model;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace NovaLab.ApiClient.Api;

/// <summary>
///     Represents a collection of functions to interact with the API endpoints
/// </summary>
public interface ITwitchNewFollowerApiSync : IApiAccessor {
    #region Synchronous Operations
    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="userId"> (optional)</param>
    /// <param name="goalId"> (optional)</param>
    /// <param name="fromDate"> (optional)</param>
    /// <param name="limit"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <returns>NewFollowerDtoApiResult</returns>
    NewFollowerDtoApiResult GetNewFollowers(string? userId = default, Guid? goalId = default, DateTime? fromDate = default, int? limit = default, int operationIndex = 0);

    /// <summary>
    /// </summary>
    /// <remarks>
    /// </remarks>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="userId"> (optional)</param>
    /// <param name="goalId"> (optional)</param>
    /// <param name="fromDate"> (optional)</param>
    /// <param name="limit"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <returns>ApiResponse of NewFollowerDtoApiResult</returns>
    ApiResponse<NewFollowerDtoApiResult> GetNewFollowersWithHttpInfo(string? userId = default, Guid? goalId = default, DateTime? fromDate = default, int? limit = default, int operationIndex = 0);
    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="postNewFollowerDto"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <returns>NewFollowerDtoApiResult</returns>
    NewFollowerDtoApiResult PostNewFollower(PostNewFollowerDto? postNewFollowerDto = default, int operationIndex = 0);

    /// <summary>
    /// </summary>
    /// <remarks>
    /// </remarks>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="postNewFollowerDto"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <returns>ApiResponse of NewFollowerDtoApiResult</returns>
    ApiResponse<NewFollowerDtoApiResult> PostNewFollowerWithHttpInfo(PostNewFollowerDto? postNewFollowerDto = default, int operationIndex = 0);
    #endregion Synchronous Operations
}

/// <summary>
///     Represents a collection of functions to interact with the API endpoints
/// </summary>
public interface ITwitchNewFollowerApiAsync : IApiAccessor {
    #region Asynchronous Operations
    /// <summary>
    /// </summary>
    /// <remarks>
    /// </remarks>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="userId"> (optional)</param>
    /// <param name="goalId"> (optional)</param>
    /// <param name="fromDate"> (optional)</param>
    /// <param name="limit"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of NewFollowerDtoApiResult</returns>
    Task<NewFollowerDtoApiResult> GetNewFollowersAsync(string? userId = default, Guid? goalId = default, DateTime? fromDate = default, int? limit = default, int operationIndex = 0, CancellationToken cancellationToken = default);

    /// <summary>
    /// </summary>
    /// <remarks>
    /// </remarks>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="userId"> (optional)</param>
    /// <param name="goalId"> (optional)</param>
    /// <param name="fromDate"> (optional)</param>
    /// <param name="limit"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ApiResponse (NewFollowerDtoApiResult)</returns>
    Task<ApiResponse<NewFollowerDtoApiResult>> GetNewFollowersWithHttpInfoAsync(string? userId = default, Guid? goalId = default, DateTime? fromDate = default, int? limit = default, int operationIndex = 0, CancellationToken cancellationToken = default);
    /// <summary>
    /// </summary>
    /// <remarks>
    /// </remarks>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="postNewFollowerDto"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of NewFollowerDtoApiResult</returns>
    Task<NewFollowerDtoApiResult> PostNewFollowerAsync(PostNewFollowerDto? postNewFollowerDto = default, int operationIndex = 0, CancellationToken cancellationToken = default);

    /// <summary>
    /// </summary>
    /// <remarks>
    /// </remarks>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="postNewFollowerDto"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ApiResponse (NewFollowerDtoApiResult)</returns>
    Task<ApiResponse<NewFollowerDtoApiResult>> PostNewFollowerWithHttpInfoAsync(PostNewFollowerDto? postNewFollowerDto = default, int operationIndex = 0, CancellationToken cancellationToken = default);
    #endregion Asynchronous Operations
}

/// <summary>
///     Represents a collection of functions to interact with the API endpoints
/// </summary>
public interface ITwitchNewFollowerApi : ITwitchNewFollowerApiSync, ITwitchNewFollowerApiAsync {
}

/// <summary>
///     Represents a collection of functions to interact with the API endpoints
/// </summary>
public class TwitchNewFollowerApi : ITwitchNewFollowerApi {
    private ExceptionFactory _exceptionFactory = (name, response) => null;

    /// <summary>
    ///     Initializes a new instance of the <see cref="TwitchNewFollowerApi" /> class.
    /// </summary>
    /// <returns></returns>
    public TwitchNewFollowerApi() : this((string)null) {
    }

    /// <summary>
    ///     Initializes a new instance of the <see cref="TwitchNewFollowerApi" /> class.
    /// </summary>
    /// <returns></returns>
    public TwitchNewFollowerApi(string basePath) {
        Configuration = ApiClient.Client.Configuration.MergeConfigurations(
        GlobalConfiguration.Instance,
        new Configuration { BasePath = basePath }
        );
        Client = new Client.ApiClient(Configuration.BasePath);
        AsynchronousClient = new Client.ApiClient(Configuration.BasePath);
        ExceptionFactory = ApiClient.Client.Configuration.DefaultExceptionFactory;
    }

    /// <summary>
    ///     Initializes a new instance of the <see cref="TwitchNewFollowerApi" /> class
    ///     using Configuration object
    /// </summary>
    /// <param name="configuration">An instance of Configuration</param>
    /// <returns></returns>
    public TwitchNewFollowerApi(Configuration configuration) {
        if (configuration == null) throw new ArgumentNullException("configuration");

        Configuration = ApiClient.Client.Configuration.MergeConfigurations(
        GlobalConfiguration.Instance,
        configuration
        );
        Client = new Client.ApiClient(Configuration.BasePath);
        AsynchronousClient = new Client.ApiClient(Configuration.BasePath);
        ExceptionFactory = ApiClient.Client.Configuration.DefaultExceptionFactory;
    }

    /// <summary>
    ///     Initializes a new instance of the <see cref="TwitchNewFollowerApi" /> class
    ///     using a Configuration object and client instance.
    /// </summary>
    /// <param name="client">The client interface for synchronous API access.</param>
    /// <param name="asyncClient">The client interface for asynchronous API access.</param>
    /// <param name="configuration">The configuration object.</param>
    public TwitchNewFollowerApi(ISynchronousClient client, IAsynchronousClient asyncClient, IReadableConfiguration configuration) {
        if (client == null) throw new ArgumentNullException("client");
        if (asyncClient == null) throw new ArgumentNullException("asyncClient");
        if (configuration == null) throw new ArgumentNullException("configuration");

        Client = client;
        AsynchronousClient = asyncClient;
        Configuration = configuration;
        ExceptionFactory = ApiClient.Client.Configuration.DefaultExceptionFactory;
    }

    /// <summary>
    ///     The client for accessing this underlying API asynchronously.
    /// </summary>
    public IAsynchronousClient AsynchronousClient { get; set; }

    /// <summary>
    ///     The client for accessing this underlying API synchronously.
    /// </summary>
    public ISynchronousClient Client { get; set; }

    /// <summary>
    ///     Gets the base path of the API client.
    /// </summary>
    /// <value>The base path</value>
    public string GetBasePath() => Configuration.BasePath;

    /// <summary>
    ///     Gets or sets the configuration object
    /// </summary>
    /// <value>An instance of the Configuration</value>
    public IReadableConfiguration Configuration { get; set; }

    /// <summary>
    ///     Provides a factory method hook for the creation of exceptions.
    /// </summary>
    public ExceptionFactory ExceptionFactory {
        get {
            if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1) {
                throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
            }
            return _exceptionFactory;
        }
        set => _exceptionFactory = value;
    }

    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="userId"> (optional)</param>
    /// <param name="goalId"> (optional)</param>
    /// <param name="fromDate"> (optional)</param>
    /// <param name="limit"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <returns>NewFollowerDtoApiResult</returns>
    public NewFollowerDtoApiResult GetNewFollowers(string? userId = default, Guid? goalId = default, DateTime? fromDate = default, int? limit = default, int operationIndex = 0) {
        ApiResponse<NewFollowerDtoApiResult> localVarResponse = GetNewFollowersWithHttpInfo(userId, goalId, fromDate, limit);
        return localVarResponse.Data;
    }

    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="userId"> (optional)</param>
    /// <param name="goalId"> (optional)</param>
    /// <param name="fromDate"> (optional)</param>
    /// <param name="limit"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <returns>ApiResponse of NewFollowerDtoApiResult</returns>
    public ApiResponse<NewFollowerDtoApiResult> GetNewFollowersWithHttpInfo(string? userId = default, Guid? goalId = default, DateTime? fromDate = default, int? limit = default, int operationIndex = 0) {
        var localVarRequestOptions = new RequestOptions();

        string[] _contentTypes = {
        };

        // to determine the Accept header
        string[] _accepts = {
            "text/plain",
            "application/json",
            "text/json"
        };

        string? localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
        if (localVarContentType != null) {
            localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
        }

        string? localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
        if (localVarAccept != null) {
            localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
        }

        if (userId != null) {
            localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("", "user-id", userId));
        }
        if (goalId != null) {
            localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("", "goal-id", goalId));
        }
        if (fromDate != null) {
            localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("", "from-date", fromDate));
        }
        if (limit != null) {
            localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("", "limit", limit));
        }

        localVarRequestOptions.Operation = "TwitchNewFollowerApi.GetNewFollowers";
        localVarRequestOptions.OperationIndex = operationIndex;


        // make the HTTP request
        ApiResponse<NewFollowerDtoApiResult>? localVarResponse = Client.Get<NewFollowerDtoApiResult>("/api/twitch/followers/new-follower", localVarRequestOptions, Configuration);
        if (ExceptionFactory != null) {
            Exception _exception = ExceptionFactory("GetNewFollowers", localVarResponse);
            if (_exception != null) {
                throw _exception;
            }
        }

        return localVarResponse;
    }

    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="userId"> (optional)</param>
    /// <param name="goalId"> (optional)</param>
    /// <param name="fromDate"> (optional)</param>
    /// <param name="limit"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of NewFollowerDtoApiResult</returns>
    public async Task<NewFollowerDtoApiResult> GetNewFollowersAsync(string? userId = default, Guid? goalId = default, DateTime? fromDate = default, int? limit = default, int operationIndex = 0, CancellationToken cancellationToken = default) {
        ApiResponse<NewFollowerDtoApiResult> localVarResponse = await GetNewFollowersWithHttpInfoAsync(userId, goalId, fromDate, limit, operationIndex, cancellationToken).ConfigureAwait(false);
        return localVarResponse.Data;
    }

    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="userId"> (optional)</param>
    /// <param name="goalId"> (optional)</param>
    /// <param name="fromDate"> (optional)</param>
    /// <param name="limit"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ApiResponse (NewFollowerDtoApiResult)</returns>
    public async Task<ApiResponse<NewFollowerDtoApiResult>> GetNewFollowersWithHttpInfoAsync(string? userId = default, Guid? goalId = default, DateTime? fromDate = default, int? limit = default, int operationIndex = 0, CancellationToken cancellationToken = default) {

        var localVarRequestOptions = new RequestOptions();

        string[] _contentTypes = {
        };

        // to determine the Accept header
        string[] _accepts = {
            "text/plain",
            "application/json",
            "text/json"
        };

        string? localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
        if (localVarContentType != null) {
            localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
        }

        string? localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
        if (localVarAccept != null) {
            localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
        }

        if (userId != null) {
            localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("", "user-id", userId));
        }
        if (goalId != null) {
            localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("", "goal-id", goalId));
        }
        if (fromDate != null) {
            localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("", "from-date", fromDate));
        }
        if (limit != null) {
            localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("", "limit", limit));
        }

        localVarRequestOptions.Operation = "TwitchNewFollowerApi.GetNewFollowers";
        localVarRequestOptions.OperationIndex = operationIndex;


        // make the HTTP request
        ApiResponse<NewFollowerDtoApiResult>? localVarResponse = await AsynchronousClient.GetAsync<NewFollowerDtoApiResult>("/api/twitch/followers/new-follower", localVarRequestOptions, Configuration, cancellationToken).ConfigureAwait(false);

        if (ExceptionFactory != null) {
            Exception _exception = ExceptionFactory("GetNewFollowers", localVarResponse);
            if (_exception != null) {
                throw _exception;
            }
        }

        return localVarResponse;
    }

    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="postNewFollowerDto"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <returns>NewFollowerDtoApiResult</returns>
    public NewFollowerDtoApiResult PostNewFollower(PostNewFollowerDto? postNewFollowerDto = default, int operationIndex = 0) {
        ApiResponse<NewFollowerDtoApiResult> localVarResponse = PostNewFollowerWithHttpInfo(postNewFollowerDto);
        return localVarResponse.Data;
    }

    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="postNewFollowerDto"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <returns>ApiResponse of NewFollowerDtoApiResult</returns>
    public ApiResponse<NewFollowerDtoApiResult> PostNewFollowerWithHttpInfo(PostNewFollowerDto? postNewFollowerDto = default, int operationIndex = 0) {
        var localVarRequestOptions = new RequestOptions();

        string[] _contentTypes = {
            "application/json",
            "text/json",
            "application/*+json"
        };

        // to determine the Accept header
        string[] _accepts = {
            "text/plain",
            "application/json",
            "text/json"
        };

        string? localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
        if (localVarContentType != null) {
            localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
        }

        string? localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
        if (localVarAccept != null) {
            localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
        }

        localVarRequestOptions.Data = postNewFollowerDto;

        localVarRequestOptions.Operation = "TwitchNewFollowerApi.PostNewFollower";
        localVarRequestOptions.OperationIndex = operationIndex;


        // make the HTTP request
        ApiResponse<NewFollowerDtoApiResult>? localVarResponse = Client.Post<NewFollowerDtoApiResult>("/api/twitch/followers/new-follower", localVarRequestOptions, Configuration);
        if (ExceptionFactory != null) {
            Exception _exception = ExceptionFactory("PostNewFollower", localVarResponse);
            if (_exception != null) {
                throw _exception;
            }
        }

        return localVarResponse;
    }

    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="postNewFollowerDto"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of NewFollowerDtoApiResult</returns>
    public async Task<NewFollowerDtoApiResult> PostNewFollowerAsync(PostNewFollowerDto? postNewFollowerDto = default, int operationIndex = 0, CancellationToken cancellationToken = default) {
        ApiResponse<NewFollowerDtoApiResult> localVarResponse = await PostNewFollowerWithHttpInfoAsync(postNewFollowerDto, operationIndex, cancellationToken).ConfigureAwait(false);
        return localVarResponse.Data;
    }

    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="postNewFollowerDto"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ApiResponse (NewFollowerDtoApiResult)</returns>
    public async Task<ApiResponse<NewFollowerDtoApiResult>> PostNewFollowerWithHttpInfoAsync(PostNewFollowerDto? postNewFollowerDto = default, int operationIndex = 0, CancellationToken cancellationToken = default) {

        var localVarRequestOptions = new RequestOptions();

        string[] _contentTypes = {
            "application/json",
            "text/json",
            "application/*+json"
        };

        // to determine the Accept header
        string[] _accepts = {
            "text/plain",
            "application/json",
            "text/json"
        };

        string? localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
        if (localVarContentType != null) {
            localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
        }

        string? localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
        if (localVarAccept != null) {
            localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
        }

        localVarRequestOptions.Data = postNewFollowerDto;

        localVarRequestOptions.Operation = "TwitchNewFollowerApi.PostNewFollower";
        localVarRequestOptions.OperationIndex = operationIndex;


        // make the HTTP request
        ApiResponse<NewFollowerDtoApiResult>? localVarResponse = await AsynchronousClient.PostAsync<NewFollowerDtoApiResult>("/api/twitch/followers/new-follower", localVarRequestOptions, Configuration, cancellationToken).ConfigureAwait(false);

        if (ExceptionFactory != null) {
            Exception _exception = ExceptionFactory("PostNewFollower", localVarResponse);
            if (_exception != null) {
                throw _exception;
            }
        }

        return localVarResponse;
    }
}
