/*
 * NovaLab API
 *
 * An ASP.NET Core Web API for managing your streams
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NovaLab.ApiClient.Client;
using NovaLab.ApiClient.Model;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace NovaLab.ApiClient.Api;

/// <summary>
///     Represents a collection of functions to interact with the API endpoints
/// </summary>
public interface ITwitchManagedRewardApiSync : IApiAccessor {
    #region Synchronous Operations
    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="userId"> (optional)</param>
    /// <param name="limit"> (optional)</param>
    /// <param name="includeInvalid"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <returns>TwitchManagedRewardDtoApiResult</returns>
    TwitchManagedRewardDtoApiResult GetManagedRewards(string? userId = default, int? limit = default, bool? includeInvalid = default, int operationIndex = 0);

    /// <summary>
    /// </summary>
    /// <remarks>
    /// </remarks>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="userId"> (optional)</param>
    /// <param name="limit"> (optional)</param>
    /// <param name="includeInvalid"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <returns>ApiResponse of TwitchManagedRewardDtoApiResult</returns>
    ApiResponse<TwitchManagedRewardDtoApiResult> GetManagedRewardsWithHttpInfo(string? userId = default, int? limit = default, bool? includeInvalid = default, int operationIndex = 0);
    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="postManagedRewardDto"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <returns>TwitchManagedRewardDtoApiResult</returns>
    TwitchManagedRewardDtoApiResult PostManagedReward(PostManagedRewardDto? postManagedRewardDto = default, int operationIndex = 0);

    /// <summary>
    /// </summary>
    /// <remarks>
    /// </remarks>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="postManagedRewardDto"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <returns>ApiResponse of TwitchManagedRewardDtoApiResult</returns>
    ApiResponse<TwitchManagedRewardDtoApiResult> PostManagedRewardWithHttpInfo(PostManagedRewardDto? postManagedRewardDto = default, int operationIndex = 0);
    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="managedRewardId"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <returns>ApiResult</returns>
    ApiResult PostNewLastCleared(string? managedRewardId = default, int operationIndex = 0);

    /// <summary>
    /// </summary>
    /// <remarks>
    /// </remarks>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="managedRewardId"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <returns>ApiResponse of ApiResult</returns>
    ApiResponse<ApiResult> PostNewLastClearedWithHttpInfo(string? managedRewardId = default, int operationIndex = 0);
    #endregion Synchronous Operations
}

/// <summary>
///     Represents a collection of functions to interact with the API endpoints
/// </summary>
public interface ITwitchManagedRewardApiAsync : IApiAccessor {
    #region Asynchronous Operations
    /// <summary>
    /// </summary>
    /// <remarks>
    /// </remarks>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="userId"> (optional)</param>
    /// <param name="limit"> (optional)</param>
    /// <param name="includeInvalid"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of TwitchManagedRewardDtoApiResult</returns>
    Task<TwitchManagedRewardDtoApiResult> GetManagedRewardsAsync(string? userId = default, int? limit = default, bool? includeInvalid = default, int operationIndex = 0, CancellationToken cancellationToken = default);

    /// <summary>
    /// </summary>
    /// <remarks>
    /// </remarks>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="userId"> (optional)</param>
    /// <param name="limit"> (optional)</param>
    /// <param name="includeInvalid"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ApiResponse (TwitchManagedRewardDtoApiResult)</returns>
    Task<ApiResponse<TwitchManagedRewardDtoApiResult>> GetManagedRewardsWithHttpInfoAsync(string? userId = default, int? limit = default, bool? includeInvalid = default, int operationIndex = 0, CancellationToken cancellationToken = default);
    /// <summary>
    /// </summary>
    /// <remarks>
    /// </remarks>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="postManagedRewardDto"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of TwitchManagedRewardDtoApiResult</returns>
    Task<TwitchManagedRewardDtoApiResult> PostManagedRewardAsync(PostManagedRewardDto? postManagedRewardDto = default, int operationIndex = 0, CancellationToken cancellationToken = default);

    /// <summary>
    /// </summary>
    /// <remarks>
    /// </remarks>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="postManagedRewardDto"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ApiResponse (TwitchManagedRewardDtoApiResult)</returns>
    Task<ApiResponse<TwitchManagedRewardDtoApiResult>> PostManagedRewardWithHttpInfoAsync(PostManagedRewardDto? postManagedRewardDto = default, int operationIndex = 0, CancellationToken cancellationToken = default);
    /// <summary>
    /// </summary>
    /// <remarks>
    /// </remarks>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="managedRewardId"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ApiResult</returns>
    Task<ApiResult> PostNewLastClearedAsync(string? managedRewardId = default, int operationIndex = 0, CancellationToken cancellationToken = default);

    /// <summary>
    /// </summary>
    /// <remarks>
    /// </remarks>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="managedRewardId"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ApiResponse (ApiResult)</returns>
    Task<ApiResponse<ApiResult>> PostNewLastClearedWithHttpInfoAsync(string? managedRewardId = default, int operationIndex = 0, CancellationToken cancellationToken = default);
    #endregion Asynchronous Operations
}

/// <summary>
///     Represents a collection of functions to interact with the API endpoints
/// </summary>
public interface ITwitchManagedRewardApi : ITwitchManagedRewardApiSync, ITwitchManagedRewardApiAsync {
}

/// <summary>
///     Represents a collection of functions to interact with the API endpoints
/// </summary>
public class TwitchManagedRewardApi : ITwitchManagedRewardApi {
    private ExceptionFactory _exceptionFactory = (name, response) => null;

    /// <summary>
    ///     Initializes a new instance of the <see cref="TwitchManagedRewardApi" /> class.
    /// </summary>
    /// <returns></returns>
    public TwitchManagedRewardApi() : this((string)null) {
    }

    /// <summary>
    ///     Initializes a new instance of the <see cref="TwitchManagedRewardApi" /> class.
    /// </summary>
    /// <returns></returns>
    public TwitchManagedRewardApi(string basePath) {
        Configuration = ApiClient.Client.Configuration.MergeConfigurations(
        GlobalConfiguration.Instance,
        new Configuration { BasePath = basePath }
        );
        Client = new Client.ApiClient(Configuration.BasePath);
        AsynchronousClient = new Client.ApiClient(Configuration.BasePath);
        ExceptionFactory = ApiClient.Client.Configuration.DefaultExceptionFactory;
    }

    /// <summary>
    ///     Initializes a new instance of the <see cref="TwitchManagedRewardApi" /> class
    ///     using Configuration object
    /// </summary>
    /// <param name="configuration">An instance of Configuration</param>
    /// <returns></returns>
    public TwitchManagedRewardApi(Configuration configuration) {
        if (configuration == null) throw new ArgumentNullException("configuration");

        Configuration = ApiClient.Client.Configuration.MergeConfigurations(
        GlobalConfiguration.Instance,
        configuration
        );
        Client = new Client.ApiClient(Configuration.BasePath);
        AsynchronousClient = new Client.ApiClient(Configuration.BasePath);
        ExceptionFactory = ApiClient.Client.Configuration.DefaultExceptionFactory;
    }

    /// <summary>
    ///     Initializes a new instance of the <see cref="TwitchManagedRewardApi" /> class
    ///     using a Configuration object and client instance.
    /// </summary>
    /// <param name="client">The client interface for synchronous API access.</param>
    /// <param name="asyncClient">The client interface for asynchronous API access.</param>
    /// <param name="configuration">The configuration object.</param>
    public TwitchManagedRewardApi(ISynchronousClient client, IAsynchronousClient asyncClient, IReadableConfiguration configuration) {
        if (client == null) throw new ArgumentNullException("client");
        if (asyncClient == null) throw new ArgumentNullException("asyncClient");
        if (configuration == null) throw new ArgumentNullException("configuration");

        Client = client;
        AsynchronousClient = asyncClient;
        Configuration = configuration;
        ExceptionFactory = ApiClient.Client.Configuration.DefaultExceptionFactory;
    }

    /// <summary>
    ///     The client for accessing this underlying API asynchronously.
    /// </summary>
    public IAsynchronousClient AsynchronousClient { get; set; }

    /// <summary>
    ///     The client for accessing this underlying API synchronously.
    /// </summary>
    public ISynchronousClient Client { get; set; }

    /// <summary>
    ///     Gets the base path of the API client.
    /// </summary>
    /// <value>The base path</value>
    public string GetBasePath() => Configuration.BasePath;

    /// <summary>
    ///     Gets or sets the configuration object
    /// </summary>
    /// <value>An instance of the Configuration</value>
    public IReadableConfiguration Configuration { get; set; }

    /// <summary>
    ///     Provides a factory method hook for the creation of exceptions.
    /// </summary>
    public ExceptionFactory ExceptionFactory {
        get {
            if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1) {
                throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
            }
            return _exceptionFactory;
        }
        set => _exceptionFactory = value;
    }

    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="userId"> (optional)</param>
    /// <param name="limit"> (optional)</param>
    /// <param name="includeInvalid"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <returns>TwitchManagedRewardDtoApiResult</returns>
    public TwitchManagedRewardDtoApiResult GetManagedRewards(string? userId = default, int? limit = default, bool? includeInvalid = default, int operationIndex = 0) {
        ApiResponse<TwitchManagedRewardDtoApiResult> localVarResponse = GetManagedRewardsWithHttpInfo(userId, limit, includeInvalid);
        return localVarResponse.Data;
    }

    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="userId"> (optional)</param>
    /// <param name="limit"> (optional)</param>
    /// <param name="includeInvalid"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <returns>ApiResponse of TwitchManagedRewardDtoApiResult</returns>
    public ApiResponse<TwitchManagedRewardDtoApiResult> GetManagedRewardsWithHttpInfo(string? userId = default, int? limit = default, bool? includeInvalid = default, int operationIndex = 0) {
        var localVarRequestOptions = new RequestOptions();

        string[] _contentTypes = {
        };

        // to determine the Accept header
        string[] _accepts = {
            "text/plain",
            "application/json",
            "text/json"
        };

        string? localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
        if (localVarContentType != null) {
            localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
        }

        string? localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
        if (localVarAccept != null) {
            localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
        }

        if (userId != null) {
            localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("", "userId", userId));
        }
        if (limit != null) {
            localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("", "limit", limit));
        }
        if (includeInvalid != null) {
            localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("", "include-invalid", includeInvalid));
        }

        localVarRequestOptions.Operation = "TwitchManagedRewardApi.GetManagedRewards";
        localVarRequestOptions.OperationIndex = operationIndex;


        // make the HTTP request
        ApiResponse<TwitchManagedRewardDtoApiResult>? localVarResponse = Client.Get<TwitchManagedRewardDtoApiResult>("/api/twitch/managed-rewards", localVarRequestOptions, Configuration);
        if (ExceptionFactory != null) {
            Exception _exception = ExceptionFactory("GetManagedRewards", localVarResponse);
            if (_exception != null) {
                throw _exception;
            }
        }

        return localVarResponse;
    }

    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="userId"> (optional)</param>
    /// <param name="limit"> (optional)</param>
    /// <param name="includeInvalid"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of TwitchManagedRewardDtoApiResult</returns>
    public async Task<TwitchManagedRewardDtoApiResult> GetManagedRewardsAsync(string? userId = default, int? limit = default, bool? includeInvalid = default, int operationIndex = 0, CancellationToken cancellationToken = default) {
        ApiResponse<TwitchManagedRewardDtoApiResult> localVarResponse = await GetManagedRewardsWithHttpInfoAsync(userId, limit, includeInvalid, operationIndex, cancellationToken).ConfigureAwait(false);
        return localVarResponse.Data;
    }

    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="userId"> (optional)</param>
    /// <param name="limit"> (optional)</param>
    /// <param name="includeInvalid"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ApiResponse (TwitchManagedRewardDtoApiResult)</returns>
    public async Task<ApiResponse<TwitchManagedRewardDtoApiResult>> GetManagedRewardsWithHttpInfoAsync(string? userId = default, int? limit = default, bool? includeInvalid = default, int operationIndex = 0, CancellationToken cancellationToken = default) {

        var localVarRequestOptions = new RequestOptions();

        string[] _contentTypes = {
        };

        // to determine the Accept header
        string[] _accepts = {
            "text/plain",
            "application/json",
            "text/json"
        };

        string? localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
        if (localVarContentType != null) {
            localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
        }

        string? localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
        if (localVarAccept != null) {
            localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
        }

        if (userId != null) {
            localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("", "userId", userId));
        }
        if (limit != null) {
            localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("", "limit", limit));
        }
        if (includeInvalid != null) {
            localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("", "include-invalid", includeInvalid));
        }

        localVarRequestOptions.Operation = "TwitchManagedRewardApi.GetManagedRewards";
        localVarRequestOptions.OperationIndex = operationIndex;


        // make the HTTP request
        ApiResponse<TwitchManagedRewardDtoApiResult>? localVarResponse = await AsynchronousClient.GetAsync<TwitchManagedRewardDtoApiResult>("/api/twitch/managed-rewards", localVarRequestOptions, Configuration, cancellationToken).ConfigureAwait(false);

        if (ExceptionFactory != null) {
            Exception _exception = ExceptionFactory("GetManagedRewards", localVarResponse);
            if (_exception != null) {
                throw _exception;
            }
        }

        return localVarResponse;
    }

    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="postManagedRewardDto"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <returns>TwitchManagedRewardDtoApiResult</returns>
    public TwitchManagedRewardDtoApiResult PostManagedReward(PostManagedRewardDto? postManagedRewardDto = default, int operationIndex = 0) {
        ApiResponse<TwitchManagedRewardDtoApiResult> localVarResponse = PostManagedRewardWithHttpInfo(postManagedRewardDto);
        return localVarResponse.Data;
    }

    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="postManagedRewardDto"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <returns>ApiResponse of TwitchManagedRewardDtoApiResult</returns>
    public ApiResponse<TwitchManagedRewardDtoApiResult> PostManagedRewardWithHttpInfo(PostManagedRewardDto? postManagedRewardDto = default, int operationIndex = 0) {
        var localVarRequestOptions = new RequestOptions();

        string[] _contentTypes = {
            "application/json",
            "text/json",
            "application/*+json"
        };

        // to determine the Accept header
        string[] _accepts = {
            "text/plain",
            "application/json",
            "text/json"
        };

        string? localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
        if (localVarContentType != null) {
            localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
        }

        string? localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
        if (localVarAccept != null) {
            localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
        }

        localVarRequestOptions.Data = postManagedRewardDto;

        localVarRequestOptions.Operation = "TwitchManagedRewardApi.PostManagedReward";
        localVarRequestOptions.OperationIndex = operationIndex;


        // make the HTTP request
        ApiResponse<TwitchManagedRewardDtoApiResult>? localVarResponse = Client.Post<TwitchManagedRewardDtoApiResult>("/api/twitch/managed-rewards", localVarRequestOptions, Configuration);
        if (ExceptionFactory != null) {
            Exception _exception = ExceptionFactory("PostManagedReward", localVarResponse);
            if (_exception != null) {
                throw _exception;
            }
        }

        return localVarResponse;
    }

    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="postManagedRewardDto"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of TwitchManagedRewardDtoApiResult</returns>
    public async Task<TwitchManagedRewardDtoApiResult> PostManagedRewardAsync(PostManagedRewardDto? postManagedRewardDto = default, int operationIndex = 0, CancellationToken cancellationToken = default) {
        ApiResponse<TwitchManagedRewardDtoApiResult> localVarResponse = await PostManagedRewardWithHttpInfoAsync(postManagedRewardDto, operationIndex, cancellationToken).ConfigureAwait(false);
        return localVarResponse.Data;
    }

    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="postManagedRewardDto"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ApiResponse (TwitchManagedRewardDtoApiResult)</returns>
    public async Task<ApiResponse<TwitchManagedRewardDtoApiResult>> PostManagedRewardWithHttpInfoAsync(PostManagedRewardDto? postManagedRewardDto = default, int operationIndex = 0, CancellationToken cancellationToken = default) {

        var localVarRequestOptions = new RequestOptions();

        string[] _contentTypes = {
            "application/json",
            "text/json",
            "application/*+json"
        };

        // to determine the Accept header
        string[] _accepts = {
            "text/plain",
            "application/json",
            "text/json"
        };

        string? localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
        if (localVarContentType != null) {
            localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
        }

        string? localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
        if (localVarAccept != null) {
            localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
        }

        localVarRequestOptions.Data = postManagedRewardDto;

        localVarRequestOptions.Operation = "TwitchManagedRewardApi.PostManagedReward";
        localVarRequestOptions.OperationIndex = operationIndex;


        // make the HTTP request
        ApiResponse<TwitchManagedRewardDtoApiResult>? localVarResponse = await AsynchronousClient.PostAsync<TwitchManagedRewardDtoApiResult>("/api/twitch/managed-rewards", localVarRequestOptions, Configuration, cancellationToken).ConfigureAwait(false);

        if (ExceptionFactory != null) {
            Exception _exception = ExceptionFactory("PostManagedReward", localVarResponse);
            if (_exception != null) {
                throw _exception;
            }
        }

        return localVarResponse;
    }

    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="managedRewardId"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <returns>ApiResult</returns>
    public ApiResult PostNewLastCleared(string? managedRewardId = default, int operationIndex = 0) {
        ApiResponse<ApiResult> localVarResponse = PostNewLastClearedWithHttpInfo(managedRewardId);
        return localVarResponse.Data;
    }

    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="managedRewardId"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <returns>ApiResponse of ApiResult</returns>
    public ApiResponse<ApiResult> PostNewLastClearedWithHttpInfo(string? managedRewardId = default, int operationIndex = 0) {
        var localVarRequestOptions = new RequestOptions();

        string[] _contentTypes = {
        };

        // to determine the Accept header
        string[] _accepts = {
            "text/plain",
            "application/json",
            "text/json"
        };

        string? localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
        if (localVarContentType != null) {
            localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
        }

        string? localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
        if (localVarAccept != null) {
            localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
        }

        if (managedRewardId != null) {
            localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("", "managedRewardId", managedRewardId));
        }

        localVarRequestOptions.Operation = "TwitchManagedRewardApi.PostNewLastCleared";
        localVarRequestOptions.OperationIndex = operationIndex;


        // make the HTTP request
        ApiResponse<ApiResult>? localVarResponse = Client.Post<ApiResult>("/api/twitch/managed-rewards/clear", localVarRequestOptions, Configuration);
        if (ExceptionFactory != null) {
            Exception _exception = ExceptionFactory("PostNewLastCleared", localVarResponse);
            if (_exception != null) {
                throw _exception;
            }
        }

        return localVarResponse;
    }

    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="managedRewardId"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ApiResult</returns>
    public async Task<ApiResult> PostNewLastClearedAsync(string? managedRewardId = default, int operationIndex = 0, CancellationToken cancellationToken = default) {
        ApiResponse<ApiResult> localVarResponse = await PostNewLastClearedWithHttpInfoAsync(managedRewardId, operationIndex, cancellationToken).ConfigureAwait(false);
        return localVarResponse.Data;
    }

    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="managedRewardId"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ApiResponse (ApiResult)</returns>
    public async Task<ApiResponse<ApiResult>> PostNewLastClearedWithHttpInfoAsync(string? managedRewardId = default, int operationIndex = 0, CancellationToken cancellationToken = default) {

        var localVarRequestOptions = new RequestOptions();

        string[] _contentTypes = {
        };

        // to determine the Accept header
        string[] _accepts = {
            "text/plain",
            "application/json",
            "text/json"
        };

        string? localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
        if (localVarContentType != null) {
            localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
        }

        string? localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
        if (localVarAccept != null) {
            localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
        }

        if (managedRewardId != null) {
            localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("", "managedRewardId", managedRewardId));
        }

        localVarRequestOptions.Operation = "TwitchManagedRewardApi.PostNewLastCleared";
        localVarRequestOptions.OperationIndex = operationIndex;


        // make the HTTP request
        ApiResponse<ApiResult>? localVarResponse = await AsynchronousClient.PostAsync<ApiResult>("/api/twitch/managed-rewards/clear", localVarRequestOptions, Configuration, cancellationToken).ConfigureAwait(false);

        if (ExceptionFactory != null) {
            Exception _exception = ExceptionFactory("PostNewLastCleared", localVarResponse);
            if (_exception != null) {
                throw _exception;
            }
        }

        return localVarResponse;
    }
}
