/*
 * NovaLab API
 *
 * An ASP.NET Core Web API for managing your streams
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NovaLab.ApiClient.Client;
using NovaLab.ApiClient.Model;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace NovaLab.ApiClient.Api;

/// <summary>
///     Represents a collection of functions to interact with the API endpoints
/// </summary>
public interface ITwitchFollowerGoalApiSync : IApiAccessor {
    #region Synchronous Operations
    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="userId"> (optional)</param>
    /// <param name="goalIds"> (optional)</param>
    /// <param name="limit"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <returns>FollowerGoalDtoApiResult</returns>
    FollowerGoalDtoApiResult GetFollowerGoals(string? userId = default, List<Guid>? goalIds = default, int? limit = default, int operationIndex = 0);

    /// <summary>
    /// </summary>
    /// <remarks>
    /// </remarks>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="userId"> (optional)</param>
    /// <param name="goalIds"> (optional)</param>
    /// <param name="limit"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <returns>ApiResponse of FollowerGoalDtoApiResult</returns>
    ApiResponse<FollowerGoalDtoApiResult> GetFollowerGoalsWithHttpInfo(string? userId = default, List<Guid>? goalIds = default, int? limit = default, int operationIndex = 0);
    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="postFollowerGoalDto"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <returns>FollowerGoalDtoApiResult</returns>
    FollowerGoalDtoApiResult PostFollowerGoal(PostFollowerGoalDto? postFollowerGoalDto = default, int operationIndex = 0);

    /// <summary>
    /// </summary>
    /// <remarks>
    /// </remarks>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="postFollowerGoalDto"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <returns>ApiResponse of FollowerGoalDtoApiResult</returns>
    ApiResponse<FollowerGoalDtoApiResult> PostFollowerGoalWithHttpInfo(PostFollowerGoalDto? postFollowerGoalDto = default, int operationIndex = 0);
    #endregion Synchronous Operations
}

/// <summary>
///     Represents a collection of functions to interact with the API endpoints
/// </summary>
public interface ITwitchFollowerGoalApiAsync : IApiAccessor {
    #region Asynchronous Operations
    /// <summary>
    /// </summary>
    /// <remarks>
    /// </remarks>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="userId"> (optional)</param>
    /// <param name="goalIds"> (optional)</param>
    /// <param name="limit"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of FollowerGoalDtoApiResult</returns>
    Task<FollowerGoalDtoApiResult> GetFollowerGoalsAsync(string? userId = default, List<Guid>? goalIds = default, int? limit = default, int operationIndex = 0, CancellationToken cancellationToken = default);

    /// <summary>
    /// </summary>
    /// <remarks>
    /// </remarks>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="userId"> (optional)</param>
    /// <param name="goalIds"> (optional)</param>
    /// <param name="limit"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ApiResponse (FollowerGoalDtoApiResult)</returns>
    Task<ApiResponse<FollowerGoalDtoApiResult>> GetFollowerGoalsWithHttpInfoAsync(string? userId = default, List<Guid>? goalIds = default, int? limit = default, int operationIndex = 0, CancellationToken cancellationToken = default);
    /// <summary>
    /// </summary>
    /// <remarks>
    /// </remarks>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="postFollowerGoalDto"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of FollowerGoalDtoApiResult</returns>
    Task<FollowerGoalDtoApiResult> PostFollowerGoalAsync(PostFollowerGoalDto? postFollowerGoalDto = default, int operationIndex = 0, CancellationToken cancellationToken = default);

    /// <summary>
    /// </summary>
    /// <remarks>
    /// </remarks>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="postFollowerGoalDto"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ApiResponse (FollowerGoalDtoApiResult)</returns>
    Task<ApiResponse<FollowerGoalDtoApiResult>> PostFollowerGoalWithHttpInfoAsync(PostFollowerGoalDto? postFollowerGoalDto = default, int operationIndex = 0, CancellationToken cancellationToken = default);
    #endregion Asynchronous Operations
}

/// <summary>
///     Represents a collection of functions to interact with the API endpoints
/// </summary>
public interface ITwitchFollowerGoalApi : ITwitchFollowerGoalApiSync, ITwitchFollowerGoalApiAsync {
}

/// <summary>
///     Represents a collection of functions to interact with the API endpoints
/// </summary>
public class TwitchFollowerGoalApi : ITwitchFollowerGoalApi {
    private ExceptionFactory _exceptionFactory = (name, response) => null;

    /// <summary>
    ///     Initializes a new instance of the <see cref="TwitchFollowerGoalApi" /> class.
    /// </summary>
    /// <returns></returns>
    public TwitchFollowerGoalApi() : this((string)null) {
    }

    /// <summary>
    ///     Initializes a new instance of the <see cref="TwitchFollowerGoalApi" /> class.
    /// </summary>
    /// <returns></returns>
    public TwitchFollowerGoalApi(string basePath) {
        Configuration = ApiClient.Client.Configuration.MergeConfigurations(
        GlobalConfiguration.Instance,
        new Configuration { BasePath = basePath }
        );
        Client = new Client.ApiClient(Configuration.BasePath);
        AsynchronousClient = new Client.ApiClient(Configuration.BasePath);
        ExceptionFactory = ApiClient.Client.Configuration.DefaultExceptionFactory;
    }

    /// <summary>
    ///     Initializes a new instance of the <see cref="TwitchFollowerGoalApi" /> class
    ///     using Configuration object
    /// </summary>
    /// <param name="configuration">An instance of Configuration</param>
    /// <returns></returns>
    public TwitchFollowerGoalApi(Configuration configuration) {
        if (configuration == null) throw new ArgumentNullException("configuration");

        Configuration = ApiClient.Client.Configuration.MergeConfigurations(
        GlobalConfiguration.Instance,
        configuration
        );
        Client = new Client.ApiClient(Configuration.BasePath);
        AsynchronousClient = new Client.ApiClient(Configuration.BasePath);
        ExceptionFactory = ApiClient.Client.Configuration.DefaultExceptionFactory;
    }

    /// <summary>
    ///     Initializes a new instance of the <see cref="TwitchFollowerGoalApi" /> class
    ///     using a Configuration object and client instance.
    /// </summary>
    /// <param name="client">The client interface for synchronous API access.</param>
    /// <param name="asyncClient">The client interface for asynchronous API access.</param>
    /// <param name="configuration">The configuration object.</param>
    public TwitchFollowerGoalApi(ISynchronousClient client, IAsynchronousClient asyncClient, IReadableConfiguration configuration) {
        if (client == null) throw new ArgumentNullException("client");
        if (asyncClient == null) throw new ArgumentNullException("asyncClient");
        if (configuration == null) throw new ArgumentNullException("configuration");

        Client = client;
        AsynchronousClient = asyncClient;
        Configuration = configuration;
        ExceptionFactory = ApiClient.Client.Configuration.DefaultExceptionFactory;
    }

    /// <summary>
    ///     The client for accessing this underlying API asynchronously.
    /// </summary>
    public IAsynchronousClient AsynchronousClient { get; set; }

    /// <summary>
    ///     The client for accessing this underlying API synchronously.
    /// </summary>
    public ISynchronousClient Client { get; set; }

    /// <summary>
    ///     Gets the base path of the API client.
    /// </summary>
    /// <value>The base path</value>
    public string GetBasePath() => Configuration.BasePath;

    /// <summary>
    ///     Gets or sets the configuration object
    /// </summary>
    /// <value>An instance of the Configuration</value>
    public IReadableConfiguration Configuration { get; set; }

    /// <summary>
    ///     Provides a factory method hook for the creation of exceptions.
    /// </summary>
    public ExceptionFactory ExceptionFactory {
        get {
            if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1) {
                throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
            }
            return _exceptionFactory;
        }
        set => _exceptionFactory = value;
    }

    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="userId"> (optional)</param>
    /// <param name="goalIds"> (optional)</param>
    /// <param name="limit"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <returns>FollowerGoalDtoApiResult</returns>
    public FollowerGoalDtoApiResult GetFollowerGoals(string? userId = default, List<Guid>? goalIds = default, int? limit = default, int operationIndex = 0) {
        ApiResponse<FollowerGoalDtoApiResult> localVarResponse = GetFollowerGoalsWithHttpInfo(userId, goalIds, limit);
        return localVarResponse.Data;
    }

    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="userId"> (optional)</param>
    /// <param name="goalIds"> (optional)</param>
    /// <param name="limit"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <returns>ApiResponse of FollowerGoalDtoApiResult</returns>
    public ApiResponse<FollowerGoalDtoApiResult> GetFollowerGoalsWithHttpInfo(string? userId = default, List<Guid>? goalIds = default, int? limit = default, int operationIndex = 0) {
        var localVarRequestOptions = new RequestOptions();

        string[] _contentTypes = {
        };

        // to determine the Accept header
        string[] _accepts = {
            "text/plain",
            "application/json",
            "text/json"
        };

        string? localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
        if (localVarContentType != null) {
            localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
        }

        string? localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
        if (localVarAccept != null) {
            localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
        }

        if (userId != null) {
            localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("", "user-id", userId));
        }
        if (goalIds != null) {
            localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("multi", "goal-ids", goalIds));
        }
        if (limit != null) {
            localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("", "limit", limit));
        }

        localVarRequestOptions.Operation = "TwitchFollowerGoalApi.GetFollowerGoals";
        localVarRequestOptions.OperationIndex = operationIndex;


        // make the HTTP request
        ApiResponse<FollowerGoalDtoApiResult>? localVarResponse = Client.Get<FollowerGoalDtoApiResult>("/api/twitch/followers/follower-goal", localVarRequestOptions, Configuration);
        if (ExceptionFactory != null) {
            Exception _exception = ExceptionFactory("GetFollowerGoals", localVarResponse);
            if (_exception != null) {
                throw _exception;
            }
        }

        return localVarResponse;
    }

    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="userId"> (optional)</param>
    /// <param name="goalIds"> (optional)</param>
    /// <param name="limit"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of FollowerGoalDtoApiResult</returns>
    public async Task<FollowerGoalDtoApiResult> GetFollowerGoalsAsync(string? userId = default, List<Guid>? goalIds = default, int? limit = default, int operationIndex = 0, CancellationToken cancellationToken = default) {
        ApiResponse<FollowerGoalDtoApiResult> localVarResponse = await GetFollowerGoalsWithHttpInfoAsync(userId, goalIds, limit, operationIndex, cancellationToken).ConfigureAwait(false);
        return localVarResponse.Data;
    }

    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="userId"> (optional)</param>
    /// <param name="goalIds"> (optional)</param>
    /// <param name="limit"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ApiResponse (FollowerGoalDtoApiResult)</returns>
    public async Task<ApiResponse<FollowerGoalDtoApiResult>> GetFollowerGoalsWithHttpInfoAsync(string? userId = default, List<Guid>? goalIds = default, int? limit = default, int operationIndex = 0, CancellationToken cancellationToken = default) {

        var localVarRequestOptions = new RequestOptions();

        string[] _contentTypes = {
        };

        // to determine the Accept header
        string[] _accepts = {
            "text/plain",
            "application/json",
            "text/json"
        };

        string? localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
        if (localVarContentType != null) {
            localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
        }

        string? localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
        if (localVarAccept != null) {
            localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
        }

        if (userId != null) {
            localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("", "user-id", userId));
        }
        if (goalIds != null) {
            localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("multi", "goal-ids", goalIds));
        }
        if (limit != null) {
            localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("", "limit", limit));
        }

        localVarRequestOptions.Operation = "TwitchFollowerGoalApi.GetFollowerGoals";
        localVarRequestOptions.OperationIndex = operationIndex;


        // make the HTTP request
        ApiResponse<FollowerGoalDtoApiResult>? localVarResponse = await AsynchronousClient.GetAsync<FollowerGoalDtoApiResult>("/api/twitch/followers/follower-goal", localVarRequestOptions, Configuration, cancellationToken).ConfigureAwait(false);

        if (ExceptionFactory != null) {
            Exception _exception = ExceptionFactory("GetFollowerGoals", localVarResponse);
            if (_exception != null) {
                throw _exception;
            }
        }

        return localVarResponse;
    }

    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="postFollowerGoalDto"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <returns>FollowerGoalDtoApiResult</returns>
    public FollowerGoalDtoApiResult PostFollowerGoal(PostFollowerGoalDto? postFollowerGoalDto = default, int operationIndex = 0) {
        ApiResponse<FollowerGoalDtoApiResult> localVarResponse = PostFollowerGoalWithHttpInfo(postFollowerGoalDto);
        return localVarResponse.Data;
    }

    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="postFollowerGoalDto"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <returns>ApiResponse of FollowerGoalDtoApiResult</returns>
    public ApiResponse<FollowerGoalDtoApiResult> PostFollowerGoalWithHttpInfo(PostFollowerGoalDto? postFollowerGoalDto = default, int operationIndex = 0) {
        var localVarRequestOptions = new RequestOptions();

        string[] _contentTypes = {
            "application/json",
            "text/json",
            "application/*+json"
        };

        // to determine the Accept header
        string[] _accepts = {
            "text/plain",
            "application/json",
            "text/json"
        };

        string? localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
        if (localVarContentType != null) {
            localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
        }

        string? localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
        if (localVarAccept != null) {
            localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
        }

        localVarRequestOptions.Data = postFollowerGoalDto;

        localVarRequestOptions.Operation = "TwitchFollowerGoalApi.PostFollowerGoal";
        localVarRequestOptions.OperationIndex = operationIndex;


        // make the HTTP request
        ApiResponse<FollowerGoalDtoApiResult>? localVarResponse = Client.Post<FollowerGoalDtoApiResult>("/api/twitch/followers/follower-goal", localVarRequestOptions, Configuration);
        if (ExceptionFactory != null) {
            Exception _exception = ExceptionFactory("PostFollowerGoal", localVarResponse);
            if (_exception != null) {
                throw _exception;
            }
        }

        return localVarResponse;
    }

    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="postFollowerGoalDto"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of FollowerGoalDtoApiResult</returns>
    public async Task<FollowerGoalDtoApiResult> PostFollowerGoalAsync(PostFollowerGoalDto? postFollowerGoalDto = default, int operationIndex = 0, CancellationToken cancellationToken = default) {
        ApiResponse<FollowerGoalDtoApiResult> localVarResponse = await PostFollowerGoalWithHttpInfoAsync(postFollowerGoalDto, operationIndex, cancellationToken).ConfigureAwait(false);
        return localVarResponse.Data;
    }

    /// <summary>
    /// </summary>
    /// <exception cref="NovaLab.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="postFollowerGoalDto"> (optional)</param>
    /// <param name="operationIndex">Index associated with the operation.</param>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ApiResponse (FollowerGoalDtoApiResult)</returns>
    public async Task<ApiResponse<FollowerGoalDtoApiResult>> PostFollowerGoalWithHttpInfoAsync(PostFollowerGoalDto? postFollowerGoalDto = default, int operationIndex = 0, CancellationToken cancellationToken = default) {

        var localVarRequestOptions = new RequestOptions();

        string[] _contentTypes = {
            "application/json",
            "text/json",
            "application/*+json"
        };

        // to determine the Accept header
        string[] _accepts = {
            "text/plain",
            "application/json",
            "text/json"
        };

        string? localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
        if (localVarContentType != null) {
            localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
        }

        string? localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
        if (localVarAccept != null) {
            localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
        }

        localVarRequestOptions.Data = postFollowerGoalDto;

        localVarRequestOptions.Operation = "TwitchFollowerGoalApi.PostFollowerGoal";
        localVarRequestOptions.OperationIndex = operationIndex;


        // make the HTTP request
        ApiResponse<FollowerGoalDtoApiResult>? localVarResponse = await AsynchronousClient.PostAsync<FollowerGoalDtoApiResult>("/api/twitch/followers/follower-goal", localVarRequestOptions, Configuration, cancellationToken).ConfigureAwait(false);

        if (ExceptionFactory != null) {
            Exception _exception = ExceptionFactory("PostFollowerGoal", localVarResponse);
            if (_exception != null) {
                throw _exception;
            }
        }

        return localVarResponse;
    }
}
